[file:mesh_n96_MG_lam.nc]
mode=auto
source=$MESH_DIR/mesh_n96_MG_lam.nc

[namelist:base_mesh]
!!f_lat_deg=
file_prefix='mesh_n96_MG_lam'
!!fplane=
topology='non_periodic'
prime_mesh_name='P48x48'

[namelist:multigrid]
chain_mesh_tags='P48x48', 'P24x24', 'P12x12', 'P6x6'

[namelist:partitioning]
partitioner='planar'
