[namelist:base_mesh]
f_lat_deg=45.0
fplane=.false.
geometry='planar'

[namelist:extrusion]
domain_height=900.0e3
number_of_layers=200

[namelist:formulation]
l_multigrid=.false.
moisture_formulation='traditional'
rotating=.false.
theta_moist_source=.true.

[namelist:helmholtz_solver]
fail_on_non_converged=.true.
gcrk=18
method='bicgstab'
monitor_convergence=.true.
preconditioner='tridiagonal'
si_pressure_a_tol=1.0e-6

[namelist:idealised]
test='specified_profiles'

[namelist:initial_temperature]
profile_data=450.0
profile_heights=0.0
profile_size=1
profile_variable='absolute'

[namelist:initial_vapour]
profile_data=0.5
profile_heights=0.0
profile_size=1
profile_variable='mr'

[namelist:initial_wind]
profile='constant_uv'
smp_init_wind=.true.

[namelist:io]
diagnostic_frequency=10

[!!namelist:multigrid]

[namelist:partitioning]
partitioner='planar'

[namelist:planet]
cp=14300.0
rd=4124.0

[namelist:transport]
panel_edge_treatment='none'
