[command]
default=mkdir -p $MESH_DIR ; mpiexec -n 1 $BIN_DIR/cubedsphere_mesh_generator mesh_generation.nml
srun=mkdir -p $MESH_DIR ; srun --ntasks=1 $BIN_DIR/cubedsphere_mesh_generator mesh_generation.nml

[namelist:cubedsphere_mesh]
edge_cells=64,32,16,8

[namelist:mesh]
mesh_maps='C64:C32', 'C16:C8', 'C8:C4'
mesh_names='C64', 'C32', 'C16', 'C8'
n_meshes=4
