[file:iodef_temp.xml]
mode=auto
source=$ROSE_SUITE_DIR/app/linear_model/file/iodef.xml

[file:mesh_C12_MG.nc]
mode=auto
source=$MESH_DIR/mesh_C12_MG.nc

[namelist:files]
ls_filename='final_ls_with_land'
start_dump_directory='$BIG_DATA_DIR/tangent-linear/Ticket354'
start_dump_filename='final_pert'

[namelist:io]
diagnostic_frequency=8

[namelist:base_mesh]
prime_mesh_name='C12'
file_prefix='mesh_C12_MG'

[namelist:multigrid]
chain_mesh_tags='C12','C6','C3'
multigrid_chain_nitems=3

[namelist:time]
calendar_origin='2016-01-01 15:00:00'
calendar_start='2016-01-01 15:00:00'

[!!namelist:multires_coupling]
dynamics_mesh_name='C12'
multires_coupling_mesh_tags='C12'
