[command]
default=make -C ${SOURCE_DIRECTORY} -j ${MAKE_THREADS} ${TARGET} \
       =PROFILE=${PROFILE} \
       =RDEF_PRECISION=${RDEF_PRECISION} \
       =BIN_DIR=${BIN_DIR} \
       =APPS_ROOT_DIR=${APPS_ROOT_DIR} \
       =CORE_ROOT_DIR=${CORE_ROOT_DIR} ||
       =(tar -cf ${CYLC_TASK_WORK_DIR}/work.tar ${WORKING_DIR} && false)

[file:$DESTINATION_DIRECTORY]
mode=mkdir

[file:$WORKING_DIR]
mode=mkdir
