[command]
default=mkdir -p $MESH_DIR ; mpiexec -n 1 $BIN_DIR/planar_mesh_generator mesh_generation.nml

[env]
mesh_generator=Planar

[!!namelist:cubedsphere_mesh]

[namelist:mesh]
mesh_maps='SEUK-64x64:SEUK-32x32','SEUK-32x32:SEUK-16x16','SEUK-16x16:SEUK-8x8'
mesh_names='SEUK-64x64','SEUK-32x32','SEUK-16x16','SEUK-8x8'
n_meshes=4
rotate_mesh=.true.
topology='non_periodic'

[namelist:planar_mesh]
domain_centre=1.69,-0.97
domain_size=1.28,0.96
edge_cells_x=64,32,16,8
edge_cells_y=64,32,16,8
periodic_x=.false.
periodic_y=.false.
create_lbc_mesh=.true.
lbc_parent_mesh='SEUK-64x64'
lbc_rim_depth=1

[namelist:rotation]
target_north_pole=177.5,37.5
