[namelist:lfric2lfric]
destination_meshfile_prefix='${MESH_DIR}/ral3_seuk/mesh_ral3_seuk'
source_meshfile_prefix='${MESH_DIR}/ral3_seuk/mesh_ral3_seuk'

[namelist:lfric2lfric]
destination_mesh_name='SEUK-64x64'
source_mesh_name='SEUK-32x32'
