[namelist:lfric2lfric]
destination_meshfile_prefix='${MESH_DIR}/ral3_uk/mesh_ral3_uk'
source_meshfile_prefix='${MESH_DIR}/ral3_uk/mesh_ral3_uk'

[namelist:lfric2lfric]
! Don't know
destination_mesh_name='P32x32'
source_mesh_name='P64x64'
