[namelist:lfric2lfric]
target_example_file="/data/users/christine.johnson/lfric_data/checkpoints/restart_lfric_atm_ral3-seuk_MG_ex1a_cce_fast-debug-32bit_tstep_0000000060"
destination_mesh_name='seuk'
destination_meshfile_prefix='${MESH_DIR}/seuk/mesh_seuk'
destination_topology='non_periodic'
dst_ancil_directory=''
dst_orography_mean_ancil_path=''
target_domain='LAM'

[namelist:partitioning(destination)]
partitioner='planar'
