[namelist:files]
checkpoint_stem_name='restart_lfric2lfric_ral_ukv_MG'

[namelist:lfric2lfric]
destination_mesh_name='ukv'
destination_meshfile_prefix='${MESH_DIR}/ukv/mesh_ukv'
destination_topology='non_periodic'
dst_ancil_directory=''
dst_orography_mean_ancil_path=''
target_domain='LAM'

[namelist:partitioning(destination)]
partitioner='planar'
