[namelist:files]
checkpoint_stem_name='restart_lfric2lfric_ral_seuk_MG'

[namelist:lfric2lfric]
destination_mesh_name='melbourne'
destination_meshfile_prefix='${MESH_DIR}/melbourne/mesh_melbourne'
destination_topology='non_periodic'
dst_ancil_directory='$BIG_DATA_DIR/ancils/proto-ral/Ticket255/Melbourne'
dst_orography_mean_ancil_path=''
target_domain='LAM'

[namelist:partitioning(destination)]
partitioner='planar'
