[ana:grepper.SingleCommandStatus(Comparison of restart file)]
# Exclude Mesh2d variable as this is a randomised integer created by XIOS
# Exclude Mesh2d_edge_nodes as um2lfric supports only cell centre fields for which
# edge nodes are not relevant. Should an edge field be supported later, the order
# of the nodes would likely be matched by a change in sign for a value in the edge field
command=nccmp -Fdf --var-diff-count=1 --exclude=Mesh2d --exclude Mesh2d_edge_nodes {0} {1}
files=$KGO_DIR/checkpoint_um2lfric_000001.nc
     =$SUITE_DIR/checkpoint_um2lfric_000001.nc
kgo_file=0
