!-----------------------------------------------------------------------------
! (C) Crown copyright 2026 Met Office. All rights reserved.
! The file LICENCE, distributed with this code, contains details of the terms
! under which the code may be used.
!-----------------------------------------------------------------------------

!> @brief   Convert temperature on geopotential height to temperature on height
!> @details The input temperature is assumed to have been generated by a model
!>          with constant gravity. For such a model physical height and 
!>          geopotential height are identical. In this kernel gravity is assumed
!>          to vary correctly with height, so that physical and geopotential
!>          heights are no longer identical. The physical height, height_phys,
!>          corresponding to height_wth, interpreted as geopotential height, is
!>          calculated. Temperature is then interpolated from height_phys onto
!>          model levels height_wth.
module regrav_geopot_kernel_mod

use argument_mod,         only: arg_type,              &
                                GH_FIELD, GH_REAL,     &
                                GH_READ, GH_READWRITE, &
                                GH_SCALAR,             &
                                CELL_COLUMN
use constants_mod,        only: r_def, i_def
use fs_continuity_mod,    only: Wtheta
use kernel_mod,           only: kernel_type

implicit none

private

!-------------------------------------------------------------------------------
! Public types
!-------------------------------------------------------------------------------
type, public, extends(kernel_type) :: regrav_geopot_kernel_type
  private
  type(arg_type) :: meta_args(3) = (/                      &
       arg_type(GH_FIELD,  GH_REAL, GH_READWRITE, Wtheta), &
       arg_type(GH_FIELD,  GH_REAL, GH_READ,      Wtheta), &
       arg_type(GH_SCALAR, GH_REAL, GH_READ)               &
       /)
  integer :: operates_on = CELL_COLUMN
contains
  procedure, nopass :: regrav_geopot_code
end type

!-------------------------------------------------------------------------------
! Contained functions/subroutines
!-------------------------------------------------------------------------------
public :: regrav_geopot_code

contains

!> @param[in]  nlayers        Number of layers
!> @param[in,out] temperature Absolute temperature field
!> @param[in]  height_wth     Height coordinate in wth
!> @param[in]  planet_radius  Radius of the planet
!> @param[in]  ndf_wt         Number of degrees of freedom per cell for wtheta
!> @param[in]  undf_wt        Total number of degrees of freedom for wtheta
!> @param[in]  map_wt         Dofmap for the cell at column base for wt
subroutine regrav_geopot_code( nlayers,       &
                               temperature,   &
                               height_wth,    &
                               planet_radius, &
                               ndf_wt,        &
                               undf_wt,       &
                               map_wt )

  implicit none

  ! Arguments
  integer(kind=i_def), intent(in) :: nlayers, &
                                     ndf_wt,  &
                                     undf_wt
  integer(kind=i_def), dimension(ndf_wt), intent(in) :: map_wt

  real(kind=r_def), dimension(undf_wt), intent(inout) :: temperature
  real(kind=r_def), dimension(undf_wt), intent(in)    :: height_wth
  real(kind=r_def),                     intent(in)    :: planet_radius

  ! Internal variables
  integer(kind=i_def) :: k
  real(kind=r_def)    :: height_phys(0:nlayers)
  real(kind=r_def)    :: temp(0:nlayers)

  ! Height corresponding to height_wth when latter represents geopotential height
  do k = 0, nlayers
    height_phys(k) =   planet_radius * height_wth(map_wt(1)+k) / &
                     ( planet_radius - height_wth(map_wt(1)+k) )
  end do

! Temporary storage for T
  do k = 0, nlayers
    temp(k) = temperature( map_wt(1) + k )
  end do

  ! Interpolate temperature from newly computed grid back onto current model grid
  call interp( nlayers+1, height_phys, temp, nlayers+1, height_wth(map_wt(1)), &
               temperature(map_wt(1)) )

end subroutine regrav_geopot_code

subroutine interp( nin, zin, fin, nout, zout, fout )

implicit none

integer(kind=i_def), intent(in)    :: nin, nout
real(kind=r_def),    intent(in)    :: zin(nin), fin(nin), zout(nout)
real(kind=r_def),    intent(inout) :: fout(nout)

integer(kind=i_def) :: kout, kin
real(kind=r_def)    :: xi

do kout = 1, nout
  if ( zout(kout) <= zin(1) ) then
    fout(kout) = fin(1)
  else if ( zout(kout) >= zin(nin) ) then
    fout(kout) = fin(nin)
  else
    do kin = 1, nin - 1
      if ( zin(kin+1) > zout(kout) ) then
        xi = ( zout(kout) - zin(kin) ) / ( zin(kin+1) - zin(kin) )
        fout(kout) = ( 1.0_r_def - xi ) * fin(kin) + xi * fin(kin+1)
      end if
    end do
  end if
end do

end subroutine interp

end module regrav_geopot_kernel_mod
