[file:mesh_C24_MG.nc]
mode=auto
source=$MESH_DIR/mesh_C24_MG.nc

[namelist:base_mesh]
!!f_lat_deg=
file_prefix='mesh_C24_MG'
!!fplane=
prime_mesh_name='C24'

[namelist:multigrid]
chain_mesh_tags='C24','C12','C6','C3'
