[namelist:jules_vegetation]
compulsory=true
description=Options for vegetation parametrisations
ns=namelist/JULES Science Settings/jules_vegetation
sort-key=Section-A12f
title=Vegetation options
url=http://metoffice.github.io/jules/namelists/jules_vegetation.nml.html

[namelist:jules_vegetation=can_rad_mod]
compulsory=true
description=Vegetation canopy radiation model
!enumeration=true
sort-key=Panel-I13
url=http://metoffice.github.io/jules/namelists/jules_vegetation.nml.html#JULES_VEGETATION::can_rad_mod
value-titles=1: Single canopy layer,
            =4: Multi-layer two stream approach,
            =5: Multi-layer with Sunfleck penetration and sunlit and shaded leaves,
            =6: Multi-layer with exponential decline in leaf N

[namelist:jules_vegetation=l_limit_canhc]
compulsory=true
description=Logical for capping vegetation canopy areal thermal heat capacity
!kind=default
sort-key=Panel-I04
type=logical
url=http://metoffice.github.io/jules/namelists/jules_vegetation.nml.html#JULES_VEGETATION::l_limit_canhc

[namelist:jules_vegetation=l_spec_veg_z0]
compulsory=true
description=Logical switch for setting explicit vegetation roughness lengths
!kind=default
sort-key=Panel-I05
type=logical
url=http://metoffice.github.io/jules/namelists/jules_vegetation.nml.html#JULES_VEGETATION::l_spec_veg_z0

[namelist:jules_vegetation=photo_model]
compulsory=true
description=Choice of photosynthesis model for C3 plants
!enumeration=true
fail-if=this == 2 and ( namelist:jules_vegetation=can_rad_mod != 1 and namelist:jules_vegetation=can_rad_mod != 5 and namelist:jules_vegetation=can_rad_mod != 6)
       =this == 3 and (namelist:jules_vegetation=stomata_model != 3)
sort-key=Panel-I20
trigger=namelist:jules_pftparm=alpha_elec_io: 2;
       =namelist:jules_pftparm=deact_jmax_io: 2;
       =namelist:jules_pftparm=deact_vcmax_io: 2;
       =namelist:jules_pftparm=jv25_ratio_io: 2;
       =namelist:jules_vegetation=photo_acclim_model: 2;
       =namelist:jules_vegetation=photo_act_model: 2;
       =namelist:jules_vegetation=photo_jv_model: 2;
url=https://metoffice.github.io/jules/namelists/jules_vegetation.nml.html#JULES_VEGETATION::photo_model
value-titles=Collatz, Farquhar, SOX Collatz
values=1,2,3
widget[rose-config-edit]=cylc8_compat.ComboBoxValueWidget
